default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: lesson-plans
  username: root
  password: "123456"
development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

staging:
  <<: *default

production:
  adapter: postgresql
  encoding: utf8
  database: lesson-plans
  username: root
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
