default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: giaoan
  username: giaoan
  password: "GiaoAn"
development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

staging:
  <<: *default

production:
  <<: *default
